import type { MenuItem } from "@/types";
import { LOCATION_IDS } from "../locations";
import { STATION_IDS } from "../stations";
import { mockProvenance } from "../provenance";

/**
 * The Market grab-and-go and packaged items. Packaged items get higher
 * confidence (~0.75) because a real deployment could read the printed label.
 */
const LOC = LOCATION_IDS.market;
const packaged = (notes?: string) =>
  mockProvenance(0.75, notes ?? "Mock nutrition modeled on a packaged label.");
const madeInHouse = (notes?: string) =>
  mockProvenance(0.5, notes ?? "Grab-and-go item; mock nutrition estimate.");

export const marketItems: MenuItem[] = [
  /* ----------------------------- Grab & Go ----------------------------- */
  {
    id: "item-market-chicken-caesar-wrap",
    name: "Chicken Caesar Wrap (Grab & Go)",
    description: "Pre-made grilled chicken Caesar wrap.",
    kind: "predefined",
    stationId: STATION_IDS.marketGrabGo,
    locationId: LOC,
    serving: { amount: 1, unit: "wrap" },
    nutrition: { calories: 540, protein: 32, carbs: 44, fat: 26, fiber: 3, sugar: 3, sodium: 1160 },
    allergens: ["wheat", "gluten", "milk", "eggs", "fish"],
    mayContainAllergens: ["soy"],
    dietaryTags: ["high-protein"],
    availability: ["all-day", "late-night"],
    price: 7.49,
    popular: true,
    provenance: madeInHouse("Contains anchovy (fish) via Caesar dressing."),
  },
  {
    id: "item-market-turkey-cheddar-sandwich",
    name: "Turkey & Cheddar Sandwich",
    description: "Roasted turkey and cheddar with lettuce on wheat bread.",
    kind: "predefined",
    stationId: STATION_IDS.marketGrabGo,
    locationId: LOC,
    serving: { amount: 1, unit: "sandwich" },
    nutrition: { calories: 480, protein: 30, carbs: 44, fat: 20, fiber: 4, sugar: 6, sodium: 1080 },
    allergens: ["wheat", "gluten", "milk"],
    mayContainAllergens: ["soy", "eggs"],
    dietaryTags: ["high-protein"],
    availability: ["all-day", "late-night"],
    price: 6.99,
    provenance: madeInHouse(),
  },
  {
    id: "item-market-southwest-salad",
    name: "Southwest Salad Bowl",
    description: "Greens, black beans, corn, peppers, cheddar, and chipotle-lime dressing.",
    kind: "predefined",
    stationId: STATION_IDS.marketGrabGo,
    locationId: LOC,
    serving: { amount: 1, unit: "bowl" },
    nutrition: { calories: 400, protein: 14, carbs: 42, fat: 20, fiber: 9, sugar: 8, sodium: 720 },
    allergens: ["milk"],
    dietaryTags: ["vegetarian", "gluten-free"],
    availability: ["all-day", "late-night"],
    price: 7.99,
    provenance: madeInHouse(),
  },
  {
    id: "item-market-overnight-oats",
    name: "Overnight Oats Cup",
    description: "Rolled oats soaked in almond milk with chia and maple.",
    kind: "predefined",
    stationId: STATION_IDS.marketGrabGo,
    locationId: LOC,
    serving: { amount: 1, unit: "cup" },
    nutrition: { calories: 320, protein: 10, carbs: 52, fat: 9, fiber: 8, sugar: 16, sodium: 90 },
    allergens: ["tree-nuts", "wheat", "gluten"],
    mayContainAllergens: ["soy", "milk"],
    dietaryTags: ["vegetarian", "vegan", "dairy-free"],
    availability: ["all-day", "late-night"],
    price: 4.49,
    provenance: madeInHouse(),
  },

  /* --------------------------- Snacks & Drinks ------------------------- */
  {
    id: "item-market-protein-shake",
    name: "Chocolate Protein Shake",
    description: "Ready-to-drink 30g protein shake.",
    kind: "predefined",
    stationId: STATION_IDS.marketSnacks,
    locationId: LOC,
    serving: { amount: 14, unit: "oz", description: "1 bottle" },
    nutrition: { calories: 160, protein: 30, carbs: 6, fat: 3, fiber: 1, sugar: 2, sodium: 200 },
    allergens: ["milk", "soy"],
    dietaryTags: ["high-protein", "gluten-free", "low-calorie", "vegetarian"],
    availability: ["all-day", "late-night"],
    price: 3.99,
    popular: true,
    provenance: packaged(),
  },
  {
    id: "item-market-greek-yogurt-cup",
    name: "Greek Yogurt Cup",
    description: "Nonfat vanilla Greek yogurt.",
    kind: "predefined",
    stationId: STATION_IDS.marketSnacks,
    locationId: LOC,
    serving: { amount: 5.3, unit: "oz", description: "1 cup" },
    nutrition: { calories: 120, protein: 15, carbs: 14, fat: 0, sugar: 10, sodium: 55, calcium: 150 },
    allergens: ["milk"],
    dietaryTags: ["vegetarian", "gluten-free", "high-protein", "low-calorie"],
    availability: ["all-day", "late-night"],
    price: 1.99,
    provenance: packaged(),
  },
  {
    id: "item-market-protein-bar",
    name: "Protein Bar",
    description: "Chocolate peanut butter protein bar.",
    kind: "predefined",
    stationId: STATION_IDS.marketSnacks,
    locationId: LOC,
    serving: { amount: 1, unit: "bar" },
    nutrition: { calories: 210, protein: 20, carbs: 22, fat: 8, fiber: 6, sugar: 6, sodium: 210 },
    allergens: ["peanuts", "milk", "soy"],
    mayContainAllergens: ["tree-nuts", "eggs"],
    dietaryTags: ["high-protein", "vegetarian"],
    availability: ["all-day", "late-night"],
    price: 2.79,
    provenance: packaged(),
  },
  {
    id: "item-market-banana",
    name: "Banana",
    description: "Fresh whole banana.",
    kind: "predefined",
    stationId: STATION_IDS.marketSnacks,
    locationId: LOC,
    serving: { amount: 1, unit: "each" },
    nutrition: { calories: 105, protein: 1, carbs: 27, fat: 0, fiber: 3, sugar: 14, sodium: 1, potassium: 422 },
    allergens: [],
    dietaryTags: ["vegan", "vegetarian", "dairy-free", "gluten-free", "low-calorie"],
    availability: ["all-day", "late-night"],
    price: 0.79,
    provenance: madeInHouse("Whole fruit; nutrition per USDA average."),
  },
  {
    id: "item-market-trail-mix",
    name: "Trail Mix",
    description: "Peanuts, almonds, raisins, and chocolate.",
    kind: "predefined",
    stationId: STATION_IDS.marketSnacks,
    locationId: LOC,
    serving: { amount: 2, unit: "oz", description: "1 bag" },
    nutrition: { calories: 260, protein: 8, carbs: 24, fat: 16, fiber: 4, sugar: 14, sodium: 60 },
    allergens: ["peanuts", "tree-nuts", "milk", "soy"],
    dietaryTags: ["vegetarian", "high-protein"],
    availability: ["all-day", "late-night"],
    price: 2.49,
    provenance: packaged(),
  },
];
