import type { MenuItem } from "@/types";
import { LOCATION_IDS } from "../locations";
import { STATION_IDS } from "../stations";
import { COMPONENT_IDS as C } from "../components";
import { mockProvenance } from "../provenance";

/**
 * Predefined items for 921 Dining. Whole-plate nutrition is a mock estimate
 * (confidence ~0.4) even though items reference components for transparency.
 */
const LOC = LOCATION_IDS.nineTwentyOne;
const prov = (notes?: string) =>
  mockProvenance(0.4, notes ?? "Whole-plate nutrition is a mock estimate; portions vary at the station.");

export const nine21Items: MenuItem[] = [
  /* ------------------------------- Grill ------------------------------- */
  {
    id: "item-921-cheeseburger",
    name: "Classic Cheeseburger",
    description: "Grilled beef patty with cheddar, lettuce, and tomato on a brioche bun.",
    kind: "predefined",
    stationId: STATION_IDS.nine21Grill,
    locationId: LOC,
    componentIds: [C.beefPatty, C.cheddarSlice, C.briocheBun, C.romaine, C.tomato],
    serving: { amount: 1, unit: "each", description: "1 burger" },
    nutrition: { calories: 540, protein: 32, carbs: 34, fat: 30, fiber: 2, sugar: 6, sodium: 520 },
    allergens: ["wheat", "gluten", "eggs", "milk"],
    mayContainAllergens: ["soy", "sesame"],
    dietaryTags: ["high-protein"],
    availability: ["lunch", "dinner"],
    price: 0,
    popular: true,
    provenance: prov(),
  },
  {
    id: "item-921-grilled-chicken-sandwich",
    name: "Grilled Chicken Sandwich",
    description: "Grilled chicken breast, lettuce, and tomato on a brioche bun.",
    kind: "predefined",
    stationId: STATION_IDS.nine21Grill,
    locationId: LOC,
    componentIds: [C.grilledChickenBreast, C.briocheBun, C.romaine, C.tomato],
    serving: { amount: 1, unit: "each", description: "1 sandwich" },
    nutrition: { calories: 430, protein: 50, carbs: 33, fat: 10, fiber: 2, sugar: 5, sodium: 640 },
    allergens: ["wheat", "gluten", "eggs", "milk"],
    mayContainAllergens: ["soy", "sesame"],
    dietaryTags: ["high-protein"],
    availability: ["lunch", "dinner"],
    provenance: prov(),
  },

  /* -------------------------------- Home ------------------------------- */
  {
    id: "item-921-herb-roasted-chicken",
    name: "Herb-Roasted Chicken with Vegetables",
    description: "Roasted bone-in chicken with a medley of seasonal vegetables.",
    kind: "predefined",
    stationId: STATION_IDS.nine21Home,
    locationId: LOC,
    serving: { amount: 1, unit: "plate" },
    nutrition: { calories: 380, protein: 40, carbs: 18, fat: 16, fiber: 4, sugar: 6, sodium: 560 },
    allergens: [],
    dietaryTags: ["high-protein", "gluten-free", "dairy-free"],
    availability: ["lunch", "dinner"],
    popular: true,
    provenance: prov(),
  },
  {
    id: "item-921-mac-and-cheese",
    name: "Baked Mac & Cheese",
    description: "Cavatappi baked in a three-cheese sauce with a toasted crumb top.",
    kind: "predefined",
    stationId: STATION_IDS.nine21Home,
    locationId: LOC,
    serving: { amount: 1, unit: "cup" },
    nutrition: { calories: 520, protein: 18, carbs: 52, fat: 26, fiber: 2, sugar: 6, sodium: 780 },
    allergens: ["milk", "wheat", "gluten"],
    dietaryTags: ["vegetarian"],
    availability: ["lunch", "dinner"],
    provenance: prov(),
  },

  /* ------------------------------ Global ------------------------------- */
  {
    id: "item-921-chicken-teriyaki",
    name: "Chicken Teriyaki Stir-Fry",
    description: "Wok-fried chicken and vegetables in teriyaki glaze over white rice.",
    kind: "predefined",
    stationId: STATION_IDS.nine21Global,
    locationId: LOC,
    serving: { amount: 1, unit: "bowl" },
    nutrition: { calories: 520, protein: 34, carbs: 68, fat: 12, fiber: 3, sugar: 16, sodium: 980 },
    allergens: ["soy", "wheat", "gluten", "sesame"],
    dietaryTags: ["high-protein", "dairy-free"],
    availability: ["lunch", "dinner"],
    provenance: prov(),
  },
  {
    id: "item-921-veg-tikka-masala",
    name: "Vegetable Tikka Masala",
    description: "Chickpeas and vegetables in a spiced tomato-cream sauce over basmati.",
    kind: "predefined",
    stationId: STATION_IDS.nine21Global,
    locationId: LOC,
    serving: { amount: 1, unit: "bowl" },
    nutrition: { calories: 480, protein: 12, carbs: 66, fat: 18, fiber: 8, sugar: 12, sodium: 720 },
    allergens: ["milk"],
    dietaryTags: ["vegetarian", "gluten-free", "spicy"],
    availability: ["lunch", "dinner"],
    provenance: prov(),
  },

  /* ---------------------------- Deli & Greens -------------------------- */
  {
    id: "item-921-chicken-caesar-salad",
    name: "Chicken Caesar Salad",
    description: "Romaine, grilled chicken, shaved parmesan, and Caesar dressing.",
    kind: "predefined",
    stationId: STATION_IDS.nine21DeliSalad,
    locationId: LOC,
    componentIds: [C.romaine, C.grilledChickenBreast, C.parmesan, C.caesarDressing],
    serving: { amount: 1, unit: "bowl" },
    nutrition: { calories: 450, protein: 50, carbs: 8, fat: 26, fiber: 2, sugar: 2, sodium: 890 },
    allergens: ["eggs", "fish", "milk"],
    dietaryTags: ["high-protein", "low-carb", "gluten-free", "keto-friendly"],
    availability: ["lunch", "dinner"],
    provenance: prov("Contains anchovy (fish) via Caesar dressing."),
  },
  {
    id: "item-921-turkey-club-wrap",
    name: "Turkey Club Wrap",
    description: "Roasted turkey, bacon, lettuce, and tomato in a whole wheat wrap.",
    kind: "predefined",
    stationId: STATION_IDS.nine21DeliSalad,
    locationId: LOC,
    componentIds: [C.wholeWheatWrap, C.romaine, C.tomato],
    serving: { amount: 1, unit: "wrap" },
    nutrition: { calories: 480, protein: 30, carbs: 40, fat: 22, fiber: 4, sugar: 4, sodium: 1180 },
    allergens: ["wheat", "gluten"],
    mayContainAllergens: ["soy", "milk"],
    dietaryTags: ["high-protein"],
    availability: ["lunch", "dinner"],
    provenance: prov(),
  },

  /* ---------------------------- Pizza & Pasta -------------------------- */
  {
    id: "item-921-cheese-pizza",
    name: "Cheese Pizza (2 slices)",
    description: "Brick-oven cheese pizza with house tomato sauce.",
    kind: "predefined",
    stationId: STATION_IDS.nine21PizzaPasta,
    locationId: LOC,
    serving: { amount: 2, unit: "slice" },
    nutrition: { calories: 560, protein: 24, carbs: 72, fat: 20, fiber: 4, sugar: 8, sodium: 1120 },
    allergens: ["milk", "wheat", "gluten"],
    mayContainAllergens: ["soy"],
    dietaryTags: ["vegetarian"],
    availability: ["lunch", "dinner"],
    popular: true,
    provenance: prov(),
  },
  {
    id: "item-921-penne-marinara",
    name: "Penne Marinara",
    description: "Penne pasta tossed in a slow-simmered marinara.",
    kind: "predefined",
    stationId: STATION_IDS.nine21PizzaPasta,
    locationId: LOC,
    serving: { amount: 1, unit: "bowl" },
    nutrition: { calories: 420, protein: 14, carbs: 78, fat: 6, fiber: 6, sugar: 10, sodium: 640 },
    allergens: ["wheat", "gluten"],
    dietaryTags: ["vegan", "vegetarian", "dairy-free"],
    availability: ["lunch", "dinner"],
    provenance: prov(),
  },

  /* -------------------------- Delicious Without ------------------------ */
  {
    id: "item-921-grilled-salmon-quinoa",
    name: "Grilled Salmon with Quinoa & Broccoli",
    description: "Prepared without common allergens at the Delicious Without station.",
    kind: "predefined",
    stationId: STATION_IDS.nine21Allergen,
    locationId: LOC,
    serving: { amount: 1, unit: "plate" },
    nutrition: { calories: 460, protein: 38, carbs: 34, fat: 20, fiber: 6, sugar: 4, sodium: 420 },
    allergens: ["fish"],
    dietaryTags: ["high-protein", "gluten-free", "dairy-free"],
    availability: ["lunch", "dinner"],
    provenance: prov("Prepared to reduce allergen cross-contact; always confirm with staff."),
  },
  {
    id: "item-921-tofu-buddha-bowl",
    name: "Herb-Roasted Tofu Buddha Bowl",
    description: "Roasted tofu, brown rice, chickpeas, and vegetables with tahini drizzle.",
    kind: "predefined",
    stationId: STATION_IDS.nine21Allergen,
    locationId: LOC,
    serving: { amount: 1, unit: "bowl" },
    nutrition: { calories: 430, protein: 20, carbs: 52, fat: 16, fiber: 10, sugar: 6, sodium: 520 },
    allergens: ["soy", "sesame"],
    dietaryTags: ["vegan", "vegetarian", "dairy-free", "gluten-free", "high-protein"],
    availability: ["lunch", "dinner"],
    provenance: prov(),
  },

  /* ------------------------------ Breakfast ---------------------------- */
  {
    id: "item-921-eggs-and-sausage",
    name: "Scrambled Eggs & Turkey Sausage",
    description: "Fluffy scrambled eggs with turkey sausage links.",
    kind: "predefined",
    stationId: STATION_IDS.nine21Bakery,
    locationId: LOC,
    componentIds: [C.scrambledEggs, C.turkeySausage],
    serving: { amount: 1, unit: "plate" },
    nutrition: { calories: 310, protein: 24, carbs: 3, fat: 22, sodium: 800 },
    allergens: ["eggs", "milk"],
    dietaryTags: ["high-protein", "gluten-free", "keto-friendly", "low-carb"],
    availability: ["breakfast", "brunch"],
    provenance: prov(),
  },
  {
    id: "item-921-blueberry-muffin",
    name: "Blueberry Muffin",
    description: "House-baked jumbo blueberry muffin.",
    kind: "predefined",
    stationId: STATION_IDS.nine21Bakery,
    locationId: LOC,
    serving: { amount: 1, unit: "each" },
    nutrition: { calories: 420, protein: 6, carbs: 58, fat: 18, fiber: 2, sugar: 32, sodium: 380 },
    allergens: ["wheat", "gluten", "eggs", "milk"],
    mayContainAllergens: ["tree-nuts", "soy"],
    dietaryTags: ["vegetarian"],
    availability: ["breakfast", "brunch", "lunch", "dinner"],
    provenance: prov(),
  },
];
